name = "jiachuang-ai"
main = "worker.js"
compatibility_date = "2024-01-01"
account_id = "390038fc8939e15f7ab4896a45343576"

[[d1_databases]]
binding = "DB"
database_name = "jiachuang-ai"
database_id = "ee449c8a-3c78-4a33-9ee5-5b6f1c391ea7"
